language: python
python:
  - "2.7"

virtualenv:
  system_site_packages: true

install:
 - git clone https://github.com/OCA/maintainer-quality-tools.git $HOME/maintainer-quality-tools
 - export PATH=$HOME/maintainer-quality-tools/travis:$PATH
 - travis_install_nightly 6.1
 - pip install coveralls flake8
 - git clone https://github.com/OCA/webkit-tools -b 6.1 $HOME/webkit-tools

script:
    - travis_run_flake8
    - travis_run_tests 6.1 $HOME/webkit-tools

after_success:
  coveralls
